project:
  type: website
  output-dir: docs

website:
  title: "tute4"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bigchayanont
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

